DROP TABLE FISHTABLE;
CREATE TABLE FISHTABLE(
        NAME NVARCHAR2(10) CONSTRAINT PK_CHAR PRIMARY KEY,
        PASSWORD NVARCHAR2(8) NOT NULL,
        STR NUMBER(10) NOT NULL,
        DEX NUMBER(10) NOT NULL,
        HP NUMBER(10) NOT NULL,
        ABILPOINT NUMBER(10),
        SCORE NUMBER(20),
        FDATE DATE);
        
        SELECT * FROM FISHTABLE;
        
DROP TABLE FISH;
CREATE TABLE FISH (
        FISHNAME NVARCHAR2(10) CONSTRAINT PK_FISH PRIMARY KEY,
        FISHSTR NUMBER(10) NOT NULL,
        FISHDEX NUMBER(10) NOT NULL,
        FISHHP NUMBER(10) NOT NULL,
        FISHSCORE NUMBER(5) NOT NULL,
        FISHPOINT NUMBER(5) NOT NULL);
        
INSERT INTO FISH (FISHNAME, FISHSTR, FISHDEX, FISHHP, FISHSCORE, FISHPOINT)
        VALUES('ÀÜÃ¬ÀÌ', 2, 2, 2, 2, 1);
INSERT INTO FISH (FISHNAME, FISHSTR, FISHDEX, FISHHP, FISHSCORE, FISHPOINT)
        VALUES('ºØ¾î', 4, 5, 8, 4, 2);
INSERT INTO FISH (FISHNAME, FISHSTR, FISHDEX, FISHHP, FISHSCORE, FISHPOINT)
        VALUES('º£½º', 12, 3, 12, 6, 3);
INSERT INTO FISH (FISHNAME, FISHSTR, FISHDEX, FISHHP, FISHSCORE, FISHPOINT)
        VALUES('Àå¾î', 10, 10, 15, 7, 3);
INSERT INTO FISH (FISHNAME, FISHSTR, FISHDEX, FISHHP, FISHSCORE, FISHPOINT)
        VALUES('Âüµ¼', 15, 13, 18, 8, 4);
INSERT INTO FISH (FISHNAME, FISHSTR, FISHDEX, FISHHP, FISHSCORE, FISHPOINT)
        VALUES('´Ù±Ý¹Ù¸®', 22, 10, 30, 10, 6);

SELECT * FROM FISH;